# due to issues with my docker-compose, this is deprecated
version: "2.3"
services:
  redis: 
    image: redis:alpine
    volumes:
      - db-data:/data
    networks:
      - frontend

  cron:
    depends_on:
      - redis
    build:
      context: .
      target: cron
    networks:
      - frontend
    environment:
      REDIS_HOST: 'redis'
      IEX_TOKEN:

  http:
    depends_on:
      - redis
    build: 
      context: .
      target: http
    networks:
      - frontend
    expose:
      - "8000"
    environment:
      REDIS_HOST: 'redis'
      IEX_TOKEN:

  bot:
    depends_on:
      - http
    build: 
      context: .
      target: bot
    networks:
      - frontend
    environment:
      API_PREFIX: 'http://http:8000'
      TWITCH_TOKEN:
      TWITCH_CHANNEL:
      BOT_USERNAME:

networks:
  # bot-http can be own network
  frontend:

volumes:
  db-data:

